#!/bin/bash
#GPL2 Based on: https://gist.github.com/G-UK/ded781ea016e2c95addba2508c6bbfbe

#INSTALL="wpasupplicant sudo aptitude ca-certificates crda fake-hwclock firmware-brcm80211 gnupg man-db manpages net-tools ntp usb-modeswitch ssh wget xz-utils xorg xorgxrdp xrdp lxqt lightdm libegl-mesa0 libgbm1 libgl1-mesa-dev libgl1-mesa-dri libglapi-mesa libglx-mesa0 libosmesa6  mesa-opencl-icd mesa-va-drivers mesa-vdpau-drivers mesa-vulkan-drivers mesa-utils curl binutils cmake git build-essential"
INSTALL="wpasupplicant sudo aptitude ca-certificates crda fake-hwclock firmware-brcm80211 gnupg man-db manpages net-tools ntp usb-modeswitch ssh wget xz-utils curl binutils cmake git build-essential dbus-x11 python3 python3-serial python3-watchdog python3-flask gpx wireless-tools xfce4 xfce4-goodies network-manager network-manager-gnome"

#Update repos
#PI repos
#echo """
#deb http://archive.raspbian.org/raspbian/ stable main contrib non-free
#deb-src http://archive.raspbian.org/raspbian/ stable main contrib non-free
#""" > /etc/apt/sources.list

echo """
deb http://ftp.us.debian.org/debian/ stable main contrib non-free
deb-src http://ftp.us.debian.org/debian/ stable main contrib non-free
""" > /etc/apt/sources.list


#Run updates
apt update -y
export DEBIAN_FRONTEND=noninteractive
apt-get -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" dist-upgrade -q -y --allow-downgrades --allow-remove-essential --allow-change-held-packages


echo """nameserver 1.1.1.1
nameserver 1.0.0.1""" > /etc/resolv.conf

echo 'Cuttleprint' > /etc/hostname


echo """127.0.0.1 localhost
127.0.1.1 Cuttleprint

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts""" > /etc/hosts


#Setup fstab
echo """
# <file system>   <dir>           <type>  <options>         <dump>  <pass>
proc              /proc           proc    defaults          0       0
/dev/mmcblk0p1    /boot           vfat    defaults          0       2
/dev/mmcblk0p2    /               ext4    defaults,noatime  0       1""" > /etc/fstab


#User
#adduser cuttleprint
groupadd spi
groupadd i2c
groupadd gpio
useradd -s /bin/bash -m -G sudo,video,adm,dialout,cdrom,audio,plugdev,games,users,input,netdev,spi,i2c,gpio cuttleprint

echo -e "cuttleprint\ncuttleprint" | passwd cuttleprint

#Install other stuff
apt-get install -y $INSTALL

cd /usr/local/bin
wget https://raw.githubusercontent.com/raspberrypi/rpi-update/master/rpi-update
chmod +x rpi-update
yes | WANT_32BIT=1 WANT_64BIT=1 WANT_PI4=1 rpi-update

echo 'dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait net.ifnames=0 8250.nr_uarts=32' > /boot/cmdline.txt
echo $'ngpu_mem=16\narm_64bit=1\ndtoverlay=vc4-fkms-v3d' > /boot/config.txt


echo '/opt/vc/lib' > /etc/ld.so.conf.d/00-vmcs.conf
echo 'Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/vc/bin"' > /etc/sudoers.d/opt-path


echo """
SUBSYSTEM=="vchiq",GROUP="video",MODE="0660"
SUBSYSTEM=="vcio",GROUP="video",MODE="0660"
SUBSYSTEM=="vc-mem",GROUP="video",MODE="0660"
SUBSYSTEM=="input", GROUP="input", MODE="0660"
SUBSYSTEM=="i2c-dev", GROUP="i2c", MODE="0660"
SUBSYSTEM=="spidev", GROUP="spi", MODE="0660"
SUBSYSTEM=="bcm2835-gpiomem", GROUP="gpio", MODE="0660"
SUBSYSTEM=="rpivid-*", GROUP="video", MODE="0660"

KERNEL=="vcsm-cma", GROUP="video", MODE="0660"

SUBSYSTEM=="gpio", GROUP="gpio", MODE="0660"
SUBSYSTEM=="gpio*", PROGRAM="/bin/sh -c '\
	chown -R root:gpio /sys/class/gpio && chmod -R 770 /sys/class/gpio;\
	chown -R root:gpio /sys/devices/virtual/gpio && chmod -R 770 /sys/devices/virtual/gpio;\
	chown -R root:gpio /sys$devpath && chmod -R 770 /sys$devpath\
'"

SUBSYSTEM=="pwm*", PROGRAM="/bin/sh -c '\
	chown -R root:gpio /sys/class/pwm && chmod -R 770 /sys/class/pwm;\
	chown -R root:gpio /sys/devices/platform/soc/*.pwm/pwm/pwmchip* && chmod -R 770 /sys/devices/platform/soc/*.pwm/pwm/pwmchip*\
'"

KERNEL=="ttyAMA[01]", PROGRAM="/bin/sh -c '\
	ALIASES=/proc/device-tree/aliases; \
	if cmp -s $ALIASES/uart0 $ALIASES/serial0; then \
		echo 0;\
	elif cmp -s $ALIASES/uart0 $ALIASES/serial1; then \
		echo 1; \
	else \
		exit 1; \
	fi\
'", SYMLINK+="serial%c"

KERNEL=="ttyS0", PROGRAM="/bin/sh -c '\
	ALIASES=/proc/device-tree/aliases; \
	if cmp -s $ALIASES/uart1 $ALIASES/serial0; then \
		echo 0; \
	elif cmp -s $ALIASES/uart1 $ALIASES/serial1; then \
		echo 1; \
	else \
		exit 1; \
	fi \
'", SYMLINK+="serial%c" """ > /etc/udev/rules.d/99-com.rules


echo "Configuring startup program"
mkdir -p /home/cuttleprint/.config/autostart/
echo """
[Desktop Entry]
Type=Application
Exec=/usr/bin/xfce4-terminal -e /Cuttleprint/startup
Hidden=false
X-MATE-Autostart-enabled=true
Name[en_US]=Cuttleprint
Name=Cuttleprint
Comment[en_US]=
Comment=
X-MATE-Autostart-Delay=0
""" > /home/cuttleprint/.config/autostart/cuttleprint.desktop
chown cuttleprint:cuttleprint -R /home/cuttleprint/.*


echo "Setup autologin"
lightdm_conf="/etc/lightdm/lightdm.conf"
sed -i '/#autologin-guest=false/c\autologin-guest=false' $lightdm_conf
sed -i '/#autologin-user=/c\autologin-user=cuttleprint' $lightdm_conf
sed -i '/#autologin-user-timeout=0/c\autologin-user-timeout=0' $lightdm_conf
