#!/usr/bin/python3
#Cuttleprint
#AGPL Copyright (C) 2022-2023  David Hamner

#apt install python3-watchdog
import os
import sys
import time
import logging
from watchdog.observers import Observer
from watchdog.events import LoggingEventHandler
import glob
import shutil

print("Sarting Cuttleprint!")
script_path = os.path.dirname(os.path.realpath(__file__))
home_dir = os.path.expanduser('~')
upload_path = f"{home_dir}/printers"
settings_file = f"{home_dir}/printer_settings.txt"

def get_printers():
    printers = []
    with open(settings_file) as fh:
        for line in fh.readlines():
            if line.strip().startswith("#"):
                continue
            if line != "":
                if ":" in line:
                    printer = line.split(":")[0].strip()
                    print(f"Looking for {printer}")
                    file_path = f"/dev/{printer}"
                    if os.path.exists(file_path):
                        printers.append(file_path)
                    else:
                        print(f"Warning, excluding missing printer {file_path}\nMake sure your printers are powered on or edit ./printer_settings.txt")
    return(printers)


if not os.path.isfile(settings_file):
    print(f"Can't find settings in {settings_file}")
    exit(2)

printers = get_printers()
print(printers)
#printers = glob.glob('/dev/ttyACM*')
if printers == []:
    print("Error finding all printers!")
    exit(1)
print(f"Printers: {printers}")


if os.path.isdir(upload_path):
    shutil.rmtree(upload_path, ignore_errors=True)
    

def setup_watch(upload_folder, handle_file_change, init_value=None):
    if not os.path.isdir(upload_folder):
        os.makedirs(upload_folder)
    
    if handle_file_change != None:
        observer = Observer()
        #objects suck hack. 
        handle_file_change.dispatch = handle_file_change
        observer.schedule(handle_file_change, upload_folder, recursive=True)
        observer.start()


def setup_path(printer_dev_file):
    name = printer_dev_file.split("/")[-1]
    
    speed, nice_name = get_printer_settings(name)
    base_folder = f"{upload_path}/{nice_name}"
    upload_folder = f"{base_folder}/upload"
    active_print = f"{base_folder}/printing"
    done_prints = f"{base_folder}/done"
    if not os.path.isdir(base_folder):
        os.makedirs(base_folder)
    if not os.path.isdir(upload_folder):
        os.makedirs(upload_folder)
    if not os.path.isdir(active_print):
        os.makedirs(active_print)
    if not os.path.isdir(done_prints):
        os.makedirs(done_prints)
    return(upload_folder)

def on_upload(event):
    might_be_code = event._src_path
    if not os.path.isfile(might_be_code):
        return
    if not might_be_code.endswith(".gcode"):
        return
    

    nice_name = might_be_code.split("/")[-3]
    printer_name = get_dev_name(nice_name)
    file_name = might_be_code.split("/")[-1]
    printer_path = f"/dev/{printer_name}"
    print(printer_name)
    print(get_printer_settings(printer_name))
    speed, nice_name = get_printer_settings(printer_name)
    log_path = f"{upload_path}/{nice_name}/log.txt"
    
    #move gcode
    is_gcode = f"{upload_path}/{nice_name}/printing/{file_name}"
    done_gcode = f"{upload_path}/{nice_name}/done/{file_name}"
    shutil.move(might_be_code, is_gcode)
    
    
    #clean up done dir
    if os.path.isfile(done_gcode):
        os.remove(done_gcode)
    
    #Add support for creator pro/GPX
    if not speed.isdigit():
        script_start = speed
        cmd = f"{script_start} '{is_gcode}' {printer_path} | tee -a {log_path} && mv {is_gcode} {done_gcode}"
    else:
        #cmd = f"{script_path}/gcode_send -d {printer_path} -b {speed} -f '{is_gcode}' && mv {is_gcode} {done_gcode}"
        cmd = f"{script_path}/gcode_send -d {printer_path} -b {speed} -f '{is_gcode}' | tee -a {log_path} && mv {is_gcode} {done_gcode}"
    print(cmd)
    
    os.system(cmd)


def get_dev_name(nice_printer_name):
    nice_printer_name = nice_printer_name.replace("_", " ")
    with open(settings_file) as fh:
        for line in fh.readlines():
            if nice_printer_name in line:
                printer_dev_name = line.split(":")[0]
                return(printer_dev_name)

def get_printer_settings(printer):
    printer = printer.replace("_", " ")
    if "/" in printer:
        printer = printer.split("/")[-1]
    with open(settings_file) as fh:
        for line in fh.readlines():
            if printer in line:
                return_data = line.split(':')[1:]
                # Clean off newline
                return_data = [x.strip() for x in return_data]
                # Replace spaces in nice name
                return_data[-1] = return_data[-1].replace(" ", "_")
                return(return_data)
    print("Warning! Printer settings not in {settings_file}\nUsing 115200")
    return(["115200"])

for printer in printers:
    watch_path = setup_path(printer)
    setup_watch(watch_path, on_upload)

while True:
    time.sleep(1)
