#!/bin/bash


cd "$(dirname "$0")"

#Make /sbin/sure to close all running programs on ctrl c
trap ctrl_c INT

function ctrl_c() {
    echo "Cleaning up..."
    kill -9 $Dice_PID $web_PID
    exit
}

#start DICE
./Dice &
Dice_PID=$!


#start web_ui
./web_ui &
#web_PID=$?


while :
do
    echo "" > ~/reboot_needed.trigger
    tail -f ~/reboot_needed.trigger | sed '/reboot/ q'
    echo -e "\n\n\nRebooting Dice\n\n\n"
    kill -9 $Dice_PID
    echo killed $Dice_PID
    #kill $(ps -ef | grep "Dice" | awk '{print $2}' | head -n 1)
    ./Dice &
    Dice_PID=$!
done
